### ISSUE TITLE
Review of FastANI

### ISSUE THREAD

**Issue by JamesJeffryes** [kbaseapps/FastANI#1]
- https://github.com/kbaseapps/FastANI/blob/master/FastANI.spec#L9
It's not required but generally good practice to annotate the spec with a specific KBase data type as done here rather than passing the ref as just strings: https://github.com/kbaseapps/DomainAnnotation/blob/master/DomainAnnotation.spec#L53-L54
- https://github.com/kbaseapps/FastANI/blob/master/Dockerfile#L40
Duplicated layer
- https://github.com/kbaseapps/FastANI/blob/master/ui/narrative/methods/fast_ani/display.yaml#L38
Can you break this into multiple lines in the yaml? Also might be nice to link to hyperlink to source repo & paper
- https://github.com/kbaseapps/FastANI/blob/master/test/FastANI_server_test.py#L4
Some unused imports: json, requests, pprint
- https://github.com/kbaseapps/FastANI/blob/master/test/FastANI_server_test.py#L126
I think you would be better off adding a unit test for your html generation code
- https://github.com/kbaseapps/FastANI/blob/master/test/FastANI_server_test.py#L130
How about some test for missing required params or params of the wrong type?
- https://github.com/kbaseapps/FastANI/blob/master/test/test_fast_ani.py#L16
Since these are test data, it's better to move the test data to a data subdirectory in `test` to distinguish it from reference data(which usually goes here)
- https://github.com/kbaseapps/FastANI/tree/master/lib/FastANI
I think it would be nice to move all your implementation logic into a subdirectory (like you have done for templates) to keep it distinct from the autogenerated code.
- https://github.com/kbaseapps/FastANI/blob/master/lib/FastANI/fast_ani_proc.py#L19
Because multiple jobs run on worker nodes, it's not a good idea to run as many processes as CPUs on the node. See an example in stringtie: https://github.com/kbaseapps/kb_stringtie/blob/master/lib/kb_stringtie/Utils/StringTieUtil.py#L652 Also look at the ui spec.json for stringtie to see how this is set to a default of two.
- https://github.com/kbaseapps/FastANI/blob/master/lib/FastANI/fast_ani_proc.py#L52
You might want to get a second opinion on this but scripts is mostly autogenerated SDK scripts so it might be better to put this in the same directory as your python code.
- https://github.com/kbaseapps/FastANI/blob/master/lib/FastANI/fast_ani_proc.py#L52
Super nitpicky but docstrings should be triple double quotes

Great job overall! I found your code quite readable and your readme documentation is great.

**Comment by jayrbolton** [comment]
> It's not required but generally good practice to annotate the spec with a specific KBase data type as done here rather than passing the ref as just strings: 

Thanks. Added this in and pushed. I was wondering why I saw a lot of type aliases in other apps. I'm still not familiar with these annotations and what their impact is.

**Comment by JamesJeffryes** [comment]
@jayrbolton Looks pretty good to me!

**Comment by jayrbolton** [comment]
Thanks for the thorough review, I'll make the updates.
Also noting this here so I don't forget:
- [ ] `fast_ani_output.create_file_links` is an unused function -- should remove

**Comment by jayrbolton** [comment]
> Because multiple jobs run on worker nodes, it's not a good idea to run as many processes as CPUs on the node. See an example in stringtie: 

@JamesJeffryes I'm a little confused about this point.. is it a bad idea because you don't want apps to overuse their resources and you want to cap their cpu usage? It seems like stringtie is just maxing the number of cpus its allowing itself to use to 2?

I was tempted to use KBParallel, but thought it might be over-engineering as the actual fastANI binary only takes a few seconds to run a dozen times serially. All the app wait time is in network requests, workspace stuff, booting containers

**Comment by JamesJeffryes** [comment]
Yes, StringTie caps itself at 2 cpus to avoid overusing the nodes
resources. You can ask Keith if there is a better value to pick but you
don't want 2 jobs on the same node trying to use all of the available CPUs.
